blank_issues_enabled: true
contact_links:
#  - name: Online Userguide and Documentation
#    url: CRAN page?
#    about: Please see the online userguide and documentation
  - name: Support
    url: https://github.com/RSE-Sheffield/golden/issues
    about: Please ask (and answer) questions here.