# Run more aggressive CRAN R CMD check
name: CRAN-style R CMD check

on:
  # Branch pushes that do not only modify other workflow files
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!.github/**"
      - ".github/scripts/**"
      - ".github/workflows/cran.yml"
  # Allow manual invocation.
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  CRAN-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
         
      # See https://github.com/r-lib/actions/tree/v2-branch/setup-r#inputs
      - name: "Install R"
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          install-r: true
      
      # See: https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies#usage
      - name: "Install Package Dependencies"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools
            tinytex
          cache: "always"
          dependencies: "TRUE"
          
      # Make pdflatex available for R CMD check
      - name: "Setup pdflatex"
        run: |
          sudo apt-get install texlive texlive-latex-extra texlive-fonts-extra
          pdflatex --version
      
      ## Output R version in user
      - name: "Print R Version"
        run: "R --version"
      
      # This step may be redundant, these dynamic files are normally commit
      # In future run this in pull requests and modify the PR?
      - name: "Rcpp compile"
        run: Rscript ".github/scripts/build.R"
        
      - name: "Build Package (R CMD)"
        run: R CMD build .
        # The output will be something like mypkg_1.0.0.tar.gz

      - name: Find tarball
        id: find-tarball
        run: |
          FILE=$(ls -1t *.tar.gz | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Extract tarball to clean environment
        run: |
          mkdir clean
          tar -xf "${{ steps.find-tarball.outputs.file }}" -C clean
          # Optional sanity check: show directory
          ls clean

      - name: Run CRAN-style check on tarball contents
        working-directory: clean
        run: |
          PKGDIR=$(ls -d */)
          echo "Checking package directory: $PKGDIR"
          R CMD check "$PKGDIR" --as-cran

      - name: Upload check results
        uses: actions/upload-artifact@v4
        with:
          name: check-output
          path: clean/**/*Rcheck
          
      - name: Fail on warnings
        run: |
          LOG=$(find clean/*/ -name "00check.log" | head -n1)
          if grep -q "WARNING" "$LOG"; then
            echo "R CMD check reported warnings!"
            exit 1
          fi